services:
  puppeteer:
    container_name: puppeteer-srv
    image: tapomix/puppeteer-srv
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://puppeteer:${SERVER_PORT}/health"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - puppeteer-net

networks:
  puppeteer-net:
    name: puppeteer-net
