services:
  puppeteer:
    # only expose the port for documentation
    expose:
      - ${SERVER_PORT:-3000}
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 2
