services:
  puppeteer:
    build:
      target: dev
    volumes:
      - ./src:/app
    # expose the port on host to test with gui tools
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    tty: true
